site_name: SE311 - Sillah (صلة) Family Health Management System
site_description: Full SE311 Software Requirements Analysis Project Documentation
site_url: https://software-requirements-analysis.shoug-tech.com
copyright: © 2026 Shoug Fawaz Alomran · All rights reserved
strict: true
hooks:
  - hooks/seo.py


theme:
  name: material
  custom_dir: overrides
  logo: logo.png
  favicon: google.png
  font:
    text: Nunito Sans
    code: JetBrains Mono
  icon:
    logo: material/ambulance
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: red
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Team: team.md

  - Phase 1 - Inception:
      - Overview: phase-1-inception/index.md
      - Business Requirements: phase-1-inception/business-requirements.md
      - Scope & Limitations: phase-1-inception/scope-and-limitations.md
      - Business Context: phase-1-inception/business-context.md

  - Phase 2 - Elicitation:
      - Overview: phase-2-elicitation/index.md
      - Elicitation Plan: phase-2-elicitation/elicitation-plan.md
      - Stakeholder Analysis: phase-2-elicitation/stakeholders.md
      - Interviews & Notes: phase-2-elicitation/elicitation-notes.md
      - Family Requirements: phase-2-elicitation/family-requirements.md
      - Healthcare Provider Requirements: phase-2-elicitation/provider-requirements.md
      - Survey: phase-2-elicitation/survey.md
      - Administrator Requirements: phase-2-elicitation/admin-requirements.md
      - Document & Competitive Analysis: phase-2-elicitation/document-analysis.md


  - Phase 3 - Analysis:
      - Overview: phase-3-analysis/index.md
      - Domain Model: phase-3-analysis/domain-model.md
      - Use Cases: phase-3-analysis/use-cases.md
      - Functional Requirements: phase-3-analysis/functional-requirements.md
      - Non-Functional Requirements: phase-3-analysis/nonfunctional-requirements.md
      - Prioritization: phase-3-analysis/prioritization.md

 # - Phase 4 – Specification:
  #    - Overview: phase-4-specification/index.md
   #   - SRS: phase-4-specification/srs.md

  # - Phase 5 – Validation:
   #   - Overview: phase-5-validation/index.md
    #  - Validation Results: phase-5-validation/validation-results.md

  # - Phase 6 – Requirements Management:
    #  - Overview: phase-6-requirements-management/index.md
     # - Change Control: phase-6-requirements-management/change-control.md
      #- Traceability Matrix: phase-6-requirements-management/traceability-matrix.md

  - Report:
      - View & Download: report/index.md

  - Conclusion: conclusion.md


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

extra_css:
  - styles/extra.css
extra_javascript:
  - javascripts/cta-footer.js
