name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - run: pip install mkdocs-material
      - run: mkdocs build --clean
      - name: Package GitHub Pages artifact
        run: |
          tar \
            --dereference --hard-dereference \
            --directory site \
            -cvf github-pages.tar \
            .
          gzip -f github-pages.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: github-pages
          path: ./github-pages.tar.gz
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
